### ISSUE TITLE
not seeing menu shortcut changes

### ISSUE THREAD

**Issue by chrwei** [christianwach/haystack-civicrm-utilities#2]
I've install on civicrm 5.79 and wordpress 6.7.1.  I found the setting and changed "Modify Shortcuts Menu" to yes.  i see no difference in the shortcut menu contents.  I am using an account that is both wordpress and civicrm admin.  I have logged off, cleared caches, not sure what else to try.

**Comment by christianwach** [comment]
@chrwei The main setting is to enable individual users to modify the menu via their "Profile" page. Have you done that additional step?

**Comment by chrwei** [comment]
ah ha!  now I see it.  this is very much non-obvious and not mentioned in the readme, which implies that it should just automatically happen.  it actually took me a long time to find the global "Modify Shortcuts Menu" option, and even that required reading the code to figure out.

**Comment by christianwach** [comment]
@chrwei Heh, well I didn't actually think anyone other than me would use this plugin! It's basically one I wrote for my own purposes while working on the development of the CiviCRM Profile Sync plugin and because the CAU shortcuts menu is aimed at users of CiviCRM rather than developers. Glad you find it useful though 😄

**Comment by christianwach** [comment]
I added some setup instructions to the readme file. Hope that helps.
